name: News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ALLOWED_USERS: ${{ secrets.ALLOWED_USERS }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          CHANNEL_LINK: ${{ secrets.CHANNEL_LINK }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          GIST_ID_ALLOWED: ${{ secrets.GIST_ID_ALLOWED }}
          GIST_ID_SENT_NEWS: ${{ secrets.GIST_ID_SENT_NEWS }}
          GIST_ID_SETTINGS: ${{ secrets.GIST_ID_SETTINGS }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SEND_TO_CHANNEL: ${{ secrets.SEND_TO_CHANNEL }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
        run: |
          python main.py
